### ISSUE TITLE
Could not open index.html in browser (Windows)

### ISSUE THREAD

**Issue by Ciget** [sandcastle/vscode-open#1]
Hi,

just have installed your plugin, but could not get it works. So, i open index.html file that located in c:\projects\somefolder\index.html, and after press ctrl+alt+o - got an error: Windows cannot find file file///c%sA/projects....

Could you please fix it?
Thanks.

**Comment by sandcastle** [comment]
@Ciget I develop on a Mac so had not seen this issue before - I will do some testing on Windows in the next day or so and get back to you with my findings. In the mean time, feel free to clone the project and debug the issue if you want.

**Comment by aaronz0** [comment]
Just `decodeURIComponent(editor.document.uri.toString())` in `extension.ts` line 45.
I don't know how to build extension, so, waiting for your update.

**Comment by sandcastle** [comment]
@Ciget / @AaronZzz - I have published an updated version with `decodeURIComponent` included.
