### ISSUE TITLE
Can't Make Keyboard Shortcut

### ISSUE THREAD

**Issue by MBetters** [sandcastle/vscode-open#12]
I would like to put something like this in my keybindings.json:

```
{
      "key": "ctrl+shift+0",
      "command": "vscode-open.openFileInDefaultApplication"
}
```

Currently, Ctrl + Alt + O is bound to VSCode's "open terminal here" action, which I'd like to keep. I'd like to bind your extension's"open file in default application" action to Ctrl + Shift + 0 (zero). However, `vscode-open` doesn't show up in available `command`s in keybindings.json.

**Comment by sandcastle** [comment]
@MBetters - are you able to send a PR for this?

**Comment by MBetters** [comment]
@sandcastle I don't have enough time to do that currently, but might sometime in the next few months.
