### ISSUE TITLE
Command `extension.open` is already defined in VS Code

### ISSUE THREAD

**Issue by jan-dolejsi** [sandcastle/vscode-open#15]
The command with Id `extension.open` is already defined in VS Code and opens an extension with a given ID in the Extensions' view. When this extension is installed, it overrides the built-in feature of VS Code. 

This extension should change the name and should prefix it with something specific to this extension, or follow the naming convention e.g. `workbench.action.files.openFileWithDefaultApplication`.

**Comment by jan-dolejsi** [comment]
Working on a proposed fix in this fork: https://github.com/jan-dolejsi/vscode-open

**Comment by sandcastle** [comment]
Great, I don't have a lot of time at the moment so any support is greatly appreciated 🙌
