### ISSUE TITLE
Nothing working on linux.

### ISSUE THREAD

**Issue by real-yfprojects** [sandcastle/vscode-open#19]
I am using Linux (Ubuntu) and installed the extension. I can see that it took 7ms to start up.
But when trying to open a file in the file explorer using the context menu, nothing happens.
No notification pops up, no program starts, there is no message in the logs and in vscode's debug console either.

The package `opn@4` works using Node.js on my machine.

**Comment by fhchl** [comment]
Same here. This extension doesn't seem to support Linux.

**Comment by sandcastle** [comment]
Pls send a PR if you can help - I have not time atm

**Comment by fhchl** [comment]
The used [open package](https://github.com/sindresorhus/open#readme) should be able to handle Linux so it's probably not difficult. I personally sadly have no experience with either TypeScript nor VS Code extensions...

**Comment by real-yfprojects** [comment]
Me too.

**Comment by MaddyGuthridge** [comment]
My guess is that this is due to it not supporting Wayland. It worked fine for me on Kubuntu 22.04, but when I changed to Fedora 36 it stopped working.

**Comment by real-yfprojects** [comment]
> My guess is that this is due to it not supporting Wayland. It worked fine for me on Kubuntu 22.04, but when I changed to Fedora 36 it stopped working.

I am using X11.

**Comment by fhchl** [comment]
Same here.

**Comment by TomSaw** [comment]
Please, make this work in Linux :)!

**Comment by MaddyGuthridge** [comment]
Ayyyy!!!!!!!

**Comment by real-yfprojects** [comment]
How can I test it? When will it be released?
