### ISSUE TITLE
Doesn't open Word doc

### ISSUE THREAD

**Issue by joshpeng** [sandcastle/vscode-open#2]
The extension is able to open my PDF files, but when I try it on a .docx file it gives an info popup that says "No editor is active."

**Comment by sandcastle** [comment]
@joshpeng can you provide a little more info about your platform (windows / mac) and whether you have office installed?

**Comment by joshpeng** [comment]
@sandcastle I am on Windows 10 with Office 2016 installed. I select the .docx file in the folder list. On the right, in the Editors it says, "The file will not be displayed in the editor because it is either binary, very large or uses an unsupported text encoding". When I press the hot key for this extension it then brings up the toast popup, "No editor is active".

**Comment by mlewand** [comment]
The same thing happens for any other non-textual files, e.g. images. I took a look on it thinking about making a pull request, but I think VS Code API doesn't provide any way to do that at the time being.

The only way (that I found in [API reference](https://code.visualstudio.com/Docs/extensionAPI/vscode-api#TextEditor)) on how can one access file path, is to get `vscode.window.activeTextEditor.document`, but there's no `vscode.window.activeTextEditor` when you're viewing file like image or so.

I reported an issue to VSCode team, let's see if they'll tell something about it: Microsoft/vscode#17703.

**Comment by sandcastle** [comment]
@mlewand thanks for looking into this 👍

**Comment by mlewand** [comment]
So by the looks of it API changes in that regard won't come any time soon, since it was closed as a duplicate of big ticket Microsoft/vscode#2582.

**Comment by sandcastle** [comment]
@joshpeng I have just merged a PR #3 (v0.1.0) that now users [opn](https://www.npmjs.com/package/opn) rather than [open](https://www.npmjs.com/package/open).

Initial testing works for me on Mac - let me know if this resolves your issues

/CC @serl

**Comment by joshpeng** [comment]
@sandcastle Looks good on my Windows. Thanks!

**Comment by sandcastle** [comment]
🆒 🍌 🍌
