### ISSUE TITLE
"No editor is active." if there are Chinese characters in path.

### ISSUE THREAD

**Issue by wzqvip** [sandcastle/vscode-open#24]
I can't open docx. and it says No editor is active. I thought i didn't use it properly, but when i switched to a non-space English path, it works. So it might due to the Chinese character in the path.

There's quite a lot Issues about the path.

**Comment by wzh4464** [comment]
Also if there is a space in the name of it.

**Comment by sandcastle** [comment]
Please send a PR if you can

**Comment by wzh4464** [comment]
Thank you. I think it has been solved in some way. It is completed in my opinion.
