### ISSUE TITLE
"Couldn't open file"

### ISSUE THREAD

**Issue by chuckkahn** [sandcastle/vscode-open#32]
This was working on MacOS Catalina but when I upgraded to MacOS Big Sur it stopped working and no amount of uninstalling, restarting, reinstalling of this extension has made it work again.

**Comment by sandcastle** [comment]
Still an issue?

**Comment by chuckkahn** [comment]
So I just went from Big Sur to Monterey and it's still an issue.   Also I never received notification regarding the May 14, 2024 response "Still an issue?" even though I am subscribed to this thread.
