### ISSUE TITLE
Open with default application is slow.

### ISSUE THREAD

**Issue by Norlandz** [sandcastle/vscode-open#34]
`Open with default application` is slow.

If I open an AA.html file with `ctrl+alt+o` `Open with default application` -- takes 20s.
If I open the AA.html file in windows explorer, then double click it -- takes 4s.

**Comment by Norlandz** [comment]
Open in External App - Visual Studio Marketplace
https://marketplace.visualstudio.com/items?itemName=YuTengjing.open-in-external-app

I found this one is faster.

**Comment by sandcastle** [comment]
Please send a PR if you can fix
